[workspace]
resolver = "2"
members = ["crates/*", "libs/*", "xtask/"]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.94.1"
repository = "https://github.com/kotlin-analyzer/kotlin-analyzer"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# local dependencies
ast = { path = "./crates/ast" }
classpath_resolver = { path = "./libs/classpath_resolver" }
lexer = { path = "./crates/lexer" }
macros = { path = "./libs/macros" }
parser = { path = "./crates/parser" }
stdx = { path = "./crates/stdx" }
syntax = { path = "./libs/syntax" }

# non-local dependencies
anyhow = "1.0.98"
assert-panic = "1.0.1"
casey = "0.4.0"
derive_more = { version = "2.1.1", features = ["debug"] }
drop_bomb = "0.1.5"
either = "1.15.0"
expect-test = "1.5.1"
inflector-plus = "0.11.7"
insta = { version = "1.37.0", features = ["ron"] }
itertools = "0.14.0"
nonempty = "0.12.0"
panic-context = "0.1.0"
pretty_assertions = "1.4.1"
prettyplease = "0.2.25"
proc-macro2 = "1.0.92"
quote = "1.0.37"
ron = "0.12"
rowan = "0.16.1"
rstest = "0.26.1"
serde = { version = "1", features = ["derive"] }
syn = "2.0.90"
tracing = "0.1.44"
xshell = "0.2.7"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
