[package]
name = "parser"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
description = "TBD"
license.workspace = true

[dependencies]
casey.workspace = true
drop_bomb.workspace = true
lexer.workspace = true
syntax.workspace = true
tracing.workspace = true

[dev-dependencies]
expect-test.workspace = true
insta.workspace = true
itertools.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true
stdx.workspace = true

[features]
verbose = []
