//! Generated by `cargo xtask codegen grammar`, do not edit by hand.

#![allow(bad_style, missing_docs, unreachable_pub)]
use crate::Edition;
#[doc = r" The kind of syntax node, e.g. `IDENT`, `USE_KW`, or `STRUCT`."]
#[derive(Debug)]
#[repr(u16)]
pub enum SyntaxKind {
    #[doc(hidden)]
    TOMBSTONE,
    #[doc(hidden)]
    EOF,
    DOLLAR,
    DOT,
    COMMA,
    L_PAREN,
    R_PAREN,
    L_SQUARE,
    R_SQUARE,
    L_CURL,
    R_CURL,
    MULT,
    MOD,
    DIV,
    ADD,
    SUB,
    SUB_ASSIGNMENT,
    INCR,
    DECR,
    CONJ,
    DISJ,
    EXCL,
    COLON,
    SEMICOLON,
    ASSIGNMENT_TOKEN,
    ADD_ASSIGNMENT,
    MULT_ASSIGNMENT,
    DIV_ASSIGNMENT,
    MOD_ASSIGNMENT,
    ARROW,
    RANGE,
    RANGE_UNTIL,
    COLON_COLON,
    AT,
    QUEST,
    L_ANGLE,
    R_ANGLE,
    LE,
    GE,
    EXCL_EQ,
    EXCL_EQ_EQ,
    EQ_EQ,
    EQ_EQ_EQ,
    AMP,
    QUOTE,
    TRIPLE_QUOTE,
    AS_KW,
    BREAK_KW,
    CLASS_KW,
    CONTINUE_KW,
    DO_KW,
    ELSE_KW,
    FALSE_KW,
    FOR_KW,
    FUN_KW,
    IF_KW,
    IN_KW,
    INTERFACE_KW,
    IS_KW,
    NULL_KW,
    OBJECT_KW,
    PACKAGE_KW,
    RETURN_KW,
    SUPER_KW,
    THIS_KW,
    THROW_KW,
    TRUE_KW,
    TRY_KW,
    TYPEALIAS_KW,
    TYPEOF_KW,
    VAL_KW,
    VAR_KW,
    WHEN_KW,
    WHILE_KW,
    NOT_IN_KW,
    NOT_IS_KW,
    AS_SAFE_KW,
    RETURN_AT_KW,
    CONTINUE_AT_KW,
    BREAK_AT_KW,
    THIS_AT_KW,
    SUPER_AT_KW,
    ABSTRACT_KW,
    ACTUAL_KW,
    ANNOTATION_KW,
    BY_KW,
    CATCH_KW,
    COMPANION_KW,
    CONSTRUCTOR_KW,
    CONST_KW,
    CONTEXT_KW,
    CONTRACT_KW,
    CROSSINLINE_KW,
    DATA_KW,
    DELEGATE_KW,
    DYNAMIC_KW,
    ENUM_KW,
    EXPECT_KW,
    EXTERNAL_KW,
    FIELD_KW,
    FILE_KW,
    FINALLY_KW,
    FINAL_KW,
    GET_KW,
    IMPORT_KW,
    INFIX_KW,
    INIT_KW,
    INLINE_KW,
    INNER_KW,
    INTERNAL_KW,
    LATEINIT_KW,
    NOINLINE_KW,
    OPEN_KW,
    OPERATOR_KW,
    OUT_KW,
    OVERRIDE_KW,
    PARAM_KW,
    PRIVATE_KW,
    PROPERTY_KW,
    PROTECTED_KW,
    PUBLIC_KW,
    RECEIVER_KW,
    REIFIED_KW,
    SEALED_KW,
    SETPARAM_KW,
    SET_KW,
    SUSPEND_KW,
    TAILREC_KW,
    VALUE_KW,
    VARARG_KW,
    WHERE_KW,
    BIN,
    BOOL,
    CHAR,
    ESCAPED,
    FLOAT,
    HEX,
    INT,
    LONG,
    TEXT,
    UNSIGNED,
    DELIMITED_COMMENT,
    ERROR,
    IDENTIFIER,
    IDENTIFIER,
    LINE_COMMENT,
    NEWLINE,
    SHEBANG_LINE,
    SHEBANG_LINE,
    WHITESPACE,
    ADDITIVE_EXPRESSION,
    ADDITIVE_OPERATOR,
    ANNOTATED_DELEGATION_SPECIFIER,
    ANNOTATED_LAMBDA,
    ANNOTATION,
    ANNOTATION_USE_SITE_TARGET,
    ANONYMOUS_FUNCTION,
    ANONYMOUS_INITIALIZER,
    ASSIGNMENT,
    ASSIGNMENT_AND_OPERATOR,
    AS_EXPRESSION,
    AS_OPERATOR,
    AS_TYPE,
    BLOCK,
    CALLABLE_REFERENCE,
    CALL_SUFFIX,
    CATCH_BLOCK,
    CLASS_BODY,
    CLASS_DECLARATION,
    CLASS_MEMBER_DECLARATIONS,
    CLASS_MODIFIER,
    CLASS_PARAMETER,
    CLASS_PARAMETERS,
    COLLECTION_LITERAL,
    COMPANION_OBJECT,
    COMPARISON,
    COMPARISON_OPERATOR,
    CONJUNCTION,
    CONSTRUCTOR_DELEGATION_CALL,
    CONSTRUCTOR_INVOCATION,
    DECLARATION,
    DEFINITELY_NON_NULLABLE_TYPE,
    DELEGATION_SPECIFIER,
    DELEGATION_SPECIFIERS,
    DIRECTLY_ASSIGNABLE_EXPRESSION,
    DISJUNCTION,
    DO_WHILE_STATEMENT,
    ELVIS,
    ELVIS_EXPRESSION,
    ENUM_CLASS_BODY,
    ENUM_ENTRIES,
    ENUM_ENTRY,
    EQUALITY,
    EQUALITY_OPERATOR,
    EXPLICIT_DELEGATION,
    EXPRESSION,
    FILE_ANNOTATION,
    FINALLY_BLOCK,
    FOR_STATEMENT,
    FUNCTION_BODY,
    FUNCTION_DECLARATION,
    FUNCTION_MODIFIER,
    FUNCTION_TYPE,
    FUNCTION_TYPE_PARAMETERS,
    FUNCTION_VALUE_PARAMETER,
    FUNCTION_VALUE_PARAMETERS,
    FUNCTION_VALUE_PARAMETER_WITH_OPTIONAL_TYPE,
    GENERIC_CALL_LIKE_COMPARISON,
    GETTER,
    IDENTIFIER,
    IF_EXPRESSION,
    IMPORT_ALIAS,
    IMPORT_HEADER,
    INDEXING_SUFFIX,
    INFIX_FUNCTION_CALL,
    INFIX_OPERATION,
    INHERITANCE_MODIFIER,
    IN_OPERATOR,
    IS_OPERATOR,
    IS_OR_IN_EXPRESSION,
    JUMP_EXPRESSION,
    KOTLIN_FILE,
    LABEL,
    LAMBDA_LITERAL,
    LAMBDA_PARAMETER,
    LAMBDA_PARAMETERS,
    LINE_STRING_CONTENT,
    LINE_STRING_EXPRESSION,
    LINE_STRING_LITERAL,
    LINE_STR_REF,
    LITERAL_CONSTANT,
    MEMBER_ACCESS_OPERATOR,
    MEMBER_MODIFIER,
    MODIFIERS,
    MULTIPLICATIVE_EXPRESSION,
    MULTIPLICATIVE_OPERATOR,
    MULTI_ANNOTATION,
    MULTI_LINE_STRING_CONTENT,
    MULTI_LINE_STRING_EXPRESSION,
    MULTI_LINE_STRING_LITERAL,
    MULTI_VARIABLE_DECLARATION,
    NAVIGATION_SUFFIX,
    NULLABLE_TYPE,
    OBJECT_DECLARATION,
    OBJECT_LITERAL,
    PACKAGE_HEADER,
    PARAMETER,
    PARAMETERS_WITH_OPTIONAL_TYPE,
    PARAMETER_MODIFIER,
    PARAMETER_MODIFIERS,
    PARAMETER_WITH_OPTIONAL_TYPE,
    PARENTHESIZED_ASSIGNABLE_EXPRESSION,
    PARENTHESIZED_DIRECTLY_ASSIGNABLE_EXPRESSION,
    PARENTHESIZED_EXPRESSION,
    PARENTHESIZED_TYPE,
    PARENTHESIZED_USER_TYPE,
    PLATFORM_MODIFIER,
    POSTFIX_UNARY_EXPRESSION,
    POSTFIX_UNARY_OPERATOR,
    PREFIX_UNARY_EXPRESSION,
    PREFIX_UNARY_OPERATOR,
    PRIMARY_CONSTRUCTOR,
    PROPERTY_DECLARATION,
    PROPERTY_DELEGATE,
    PROPERTY_MODIFIER,
    RANGE_EXPRESSION,
    RANGE_TEST,
    RECEIVER_TYPE,
    REIFICATION_MODIFIER,
    SCRIPT,
    SECONDARY_CONSTRUCTOR,
    SETTER,
    SHEBANG_LINE,
    SIMPLE_IDENTIFIER,
    SIMPLE_USER_TYPE,
    SINGLE_ANNOTATION,
    STATEMENT,
    STATEMENTS,
    STRING_LITERAL,
    STR_EXPR_START,
    SUPER_EXPRESSION,
    THIS_EXPRESSION,
    TOP_LEVEL_OBJECT,
    TRY_EXPRESSION,
    TYPE,
    TYPE_ALIAS,
    TYPE_ARGUMENTS,
    TYPE_CONSTRAINT,
    TYPE_CONSTRAINTS,
    TYPE_MODIFIER,
    TYPE_MODIFIERS,
    TYPE_PARAMETER,
    TYPE_PARAMETERS,
    TYPE_PARAMETER_MODIFIERS,
    TYPE_PROJECTION,
    TYPE_PROJECTION_MODIFIERS,
    TYPE_REFERENCE,
    TYPE_TEST,
    USER_TYPE,
    VALUE_ARGUMENT,
    VALUE_ARGUMENTS,
    VARIABLE_DECLARATION,
    VARIANCE_MODIFIER,
    VISIBILITY_MODIFIER,
    WHEN_ENTRY,
    WHEN_EXPRESSION,
    WHEN_SUBJECT,
    WHILE_STATEMENT,
    #[doc(hidden)]
    __LAST,
}
use self::SyntaxKind::*;
impl SyntaxKind {
    #[allow(unreachable_patterns)]
    pub const fn text(self) -> &'static str {
        match self {
            TOMBSTONE
            | EOF
            | __LAST
            | BIN
            | BOOL
            | CHAR
            | ESCAPED
            | FLOAT
            | HEX
            | INT
            | LONG
            | TEXT
            | UNSIGNED
            | ADDITIVE_EXPRESSION
            | ADDITIVE_OPERATOR
            | ANNOTATED_DELEGATION_SPECIFIER
            | ANNOTATED_LAMBDA
            | ANNOTATION
            | ANNOTATION_USE_SITE_TARGET
            | ANONYMOUS_FUNCTION
            | ANONYMOUS_INITIALIZER
            | ASSIGNMENT
            | ASSIGNMENT_AND_OPERATOR
            | AS_EXPRESSION
            | AS_OPERATOR
            | AS_TYPE
            | BLOCK
            | CALLABLE_REFERENCE
            | CALL_SUFFIX
            | CATCH_BLOCK
            | CLASS_BODY
            | CLASS_DECLARATION
            | CLASS_MEMBER_DECLARATIONS
            | CLASS_MODIFIER
            | CLASS_PARAMETER
            | CLASS_PARAMETERS
            | COLLECTION_LITERAL
            | COMPANION_OBJECT
            | COMPARISON
            | COMPARISON_OPERATOR
            | CONJUNCTION
            | CONSTRUCTOR_DELEGATION_CALL
            | CONSTRUCTOR_INVOCATION
            | DECLARATION
            | DEFINITELY_NON_NULLABLE_TYPE
            | DELEGATION_SPECIFIER
            | DELEGATION_SPECIFIERS
            | DIRECTLY_ASSIGNABLE_EXPRESSION
            | DISJUNCTION
            | DO_WHILE_STATEMENT
            | ELVIS
            | ELVIS_EXPRESSION
            | ENUM_CLASS_BODY
            | ENUM_ENTRIES
            | ENUM_ENTRY
            | EQUALITY
            | EQUALITY_OPERATOR
            | EXPLICIT_DELEGATION
            | EXPRESSION
            | FILE_ANNOTATION
            | FINALLY_BLOCK
            | FOR_STATEMENT
            | FUNCTION_BODY
            | FUNCTION_DECLARATION
            | FUNCTION_MODIFIER
            | FUNCTION_TYPE
            | FUNCTION_TYPE_PARAMETERS
            | FUNCTION_VALUE_PARAMETER
            | FUNCTION_VALUE_PARAMETERS
            | FUNCTION_VALUE_PARAMETER_WITH_OPTIONAL_TYPE
            | GENERIC_CALL_LIKE_COMPARISON
            | GETTER
            | IDENTIFIER
            | IF_EXPRESSION
            | IMPORT_ALIAS
            | IMPORT_HEADER
            | INDEXING_SUFFIX
            | INFIX_FUNCTION_CALL
            | INFIX_OPERATION
            | INHERITANCE_MODIFIER
            | IN_OPERATOR
            | IS_OPERATOR
            | IS_OR_IN_EXPRESSION
            | JUMP_EXPRESSION
            | KOTLIN_FILE
            | LABEL
            | LAMBDA_LITERAL
            | LAMBDA_PARAMETER
            | LAMBDA_PARAMETERS
            | LINE_STRING_CONTENT
            | LINE_STRING_EXPRESSION
            | LINE_STRING_LITERAL
            | LINE_STR_REF
            | LITERAL_CONSTANT
            | MEMBER_ACCESS_OPERATOR
            | MEMBER_MODIFIER
            | MODIFIERS
            | MULTIPLICATIVE_EXPRESSION
            | MULTIPLICATIVE_OPERATOR
            | MULTI_ANNOTATION
            | MULTI_LINE_STRING_CONTENT
            | MULTI_LINE_STRING_EXPRESSION
            | MULTI_LINE_STRING_LITERAL
            | MULTI_VARIABLE_DECLARATION
            | NAVIGATION_SUFFIX
            | NULLABLE_TYPE
            | OBJECT_DECLARATION
            | OBJECT_LITERAL
            | PACKAGE_HEADER
            | PARAMETER
            | PARAMETERS_WITH_OPTIONAL_TYPE
            | PARAMETER_MODIFIER
            | PARAMETER_MODIFIERS
            | PARAMETER_WITH_OPTIONAL_TYPE
            | PARENTHESIZED_ASSIGNABLE_EXPRESSION
            | PARENTHESIZED_DIRECTLY_ASSIGNABLE_EXPRESSION
            | PARENTHESIZED_EXPRESSION
            | PARENTHESIZED_TYPE
            | PARENTHESIZED_USER_TYPE
            | PLATFORM_MODIFIER
            | POSTFIX_UNARY_EXPRESSION
            | POSTFIX_UNARY_OPERATOR
            | PREFIX_UNARY_EXPRESSION
            | PREFIX_UNARY_OPERATOR
            | PRIMARY_CONSTRUCTOR
            | PROPERTY_DECLARATION
            | PROPERTY_DELEGATE
            | PROPERTY_MODIFIER
            | RANGE_EXPRESSION
            | RANGE_TEST
            | RECEIVER_TYPE
            | REIFICATION_MODIFIER
            | SCRIPT
            | SECONDARY_CONSTRUCTOR
            | SETTER
            | SHEBANG_LINE
            | SIMPLE_IDENTIFIER
            | SIMPLE_USER_TYPE
            | SINGLE_ANNOTATION
            | STATEMENT
            | STATEMENTS
            | STRING_LITERAL
            | STR_EXPR_START
            | SUPER_EXPRESSION
            | THIS_EXPRESSION
            | TOP_LEVEL_OBJECT
            | TRY_EXPRESSION
            | TYPE
            | TYPE_ALIAS
            | TYPE_ARGUMENTS
            | TYPE_CONSTRAINT
            | TYPE_CONSTRAINTS
            | TYPE_MODIFIER
            | TYPE_MODIFIERS
            | TYPE_PARAMETER
            | TYPE_PARAMETERS
            | TYPE_PARAMETER_MODIFIERS
            | TYPE_PROJECTION
            | TYPE_PROJECTION_MODIFIERS
            | TYPE_REFERENCE
            | TYPE_TEST
            | USER_TYPE
            | VALUE_ARGUMENT
            | VALUE_ARGUMENTS
            | VARIABLE_DECLARATION
            | VARIANCE_MODIFIER
            | VISIBILITY_MODIFIER
            | WHEN_ENTRY
            | WHEN_EXPRESSION
            | WHEN_SUBJECT
            | WHILE_STATEMENT
            | DELIMITED_COMMENT
            | ERROR
            | IDENTIFIER
            | IDENTIFIER
            | LINE_COMMENT
            | NEWLINE
            | SHEBANG_LINE
            | SHEBANG_LINE
            | WHITESPACE => panic!("no text for these `SyntaxKind`s"),
            DOLLAR => "$",
            DOT => ".",
            COMMA => ",",
            L_PAREN => "(",
            R_PAREN => ")",
            L_SQUARE => "[",
            R_SQUARE => "]",
            L_CURL => "{",
            R_CURL => "}",
            MULT => "*",
            MOD => "%",
            DIV => "/",
            ADD => "+",
            SUB => "-",
            SUB_ASSIGNMENT => "-=",
            INCR => "++",
            DECR => "--",
            CONJ => "&&",
            DISJ => "||",
            EXCL => "!",
            COLON => ":",
            SEMICOLON => ";",
            ASSIGNMENT_TOKEN => "=",
            ADD_ASSIGNMENT => "+=",
            MULT_ASSIGNMENT => "*=",
            DIV_ASSIGNMENT => "/=",
            MOD_ASSIGNMENT => "%=",
            ARROW => "->",
            RANGE => "..",
            RANGE_UNTIL => "..<",
            COLON_COLON => "::",
            AT => "@",
            QUEST => "?",
            L_ANGLE => "<",
            R_ANGLE => ">",
            LE => "<=",
            GE => ">=",
            EXCL_EQ => "!=",
            EXCL_EQ_EQ => "!==",
            EQ_EQ => "==",
            EQ_EQ_EQ => "===",
            AMP => "&",
            QUOTE => "\"",
            TRIPLE_QUOTE => "\"\"\"",
            AS_KW => "as",
            BREAK_KW => "break",
            CLASS_KW => "class",
            CONTINUE_KW => "continue",
            DO_KW => "do",
            ELSE_KW => "else",
            FALSE_KW => "false",
            FOR_KW => "for",
            FUN_KW => "fun",
            IF_KW => "if",
            IN_KW => "in",
            INTERFACE_KW => "interface",
            IS_KW => "is",
            NULL_KW => "null",
            OBJECT_KW => "object",
            PACKAGE_KW => "package",
            RETURN_KW => "return",
            SUPER_KW => "super",
            THIS_KW => "this",
            THROW_KW => "throw",
            TRUE_KW => "true",
            TRY_KW => "try",
            TYPEALIAS_KW => "typealias",
            TYPEOF_KW => "typeof",
            VAL_KW => "val",
            VAR_KW => "var",
            WHEN_KW => "when",
            WHILE_KW => "while",
            ABSTRACT_KW => "abstract",
            ACTUAL_KW => "actual",
            ANNOTATION_KW => "annotation",
            BY_KW => "by",
            CATCH_KW => "catch",
            COMPANION_KW => "companion",
            CONST_KW => "const",
            CONSTRUCTOR_KW => "constructor",
            CONTEXT_KW => "context",
            CROSSINLINE_KW => "crossinline",
            DATA_KW => "data",
            DELEGATE_KW => "delegate",
            DYNAMIC_KW => "dynamic",
            ENUM_KW => "enum",
            EXPECT_KW => "expect",
            EXTERNAL_KW => "external",
            FIELD_KW => "field",
            FILE_KW => "file",
            FINAL_KW => "final",
            FINALLY_KW => "finally",
            GET_KW => "get",
            IMPORT_KW => "import",
            INFIX_KW => "infix",
            INIT_KW => "init",
            INLINE_KW => "inline",
            INNER_KW => "inner",
            INTERNAL_KW => "internal",
            LATEINIT_KW => "lateinit",
            NOINLINE_KW => "noinline",
            OPEN_KW => "open",
            OPERATOR_KW => "operator",
            OUT_KW => "out",
            OVERRIDE_KW => "override",
            PARAM_KW => "param",
            PRIVATE_KW => "private",
            PROPERTY_KW => "property",
            PROTECTED_KW => "protected",
            PUBLIC_KW => "public",
            RECEIVER_KW => "receiver",
            REIFIED_KW => "reified",
            SEALED_KW => "sealed",
            SET_KW => "set",
            SETPARAM_KW => "setparam",
            SUSPEND_KW => "suspend",
            TAILREC_KW => "tailrec",
            VALUE_KW => "value",
            VARARG_KW => "vararg",
            WHERE_KW => "where",
            CONTEXT_KW => "context",
            CONTRACT_KW => "contract",
            VALUE_KW => "value",
        }
    }
    #[doc = r" Checks whether this syntax kind is a strict keyword for the given version."]
    #[doc = r" Strict keywords are identifiers that are always considered keywords."]
    pub fn is_strict_keyword(self, version: Version) -> bool {
        matches!(
            self,
            AS_KW
                | BREAK_KW
                | CLASS_KW
                | CONTINUE_KW
                | DO_KW
                | ELSE_KW
                | FALSE_KW
                | FOR_KW
                | FUN_KW
                | IF_KW
                | IN_KW
                | INTERFACE_KW
                | IS_KW
                | NULL_KW
                | OBJECT_KW
                | PACKAGE_KW
                | RETURN_KW
                | SUPER_KW
                | THIS_KW
                | THROW_KW
                | TRUE_KW
                | TRY_KW
                | TYPEALIAS_KW
                | TYPEOF_KW
                | VAL_KW
                | VAR_KW
                | WHEN_KW
                | WHILE_KW
                | NOT_IN_KW
                | NOT_IS_KW
                | AS_SAFE_KW
                | RETURN_AT_KW
                | CONTINUE_AT_KW
                | BREAK_AT_KW
                | THIS_AT_KW
                | SUPER_AT_KW
        ) || match self {
            CONTEXT_KW if Version::V1_7 <= version => true,
            CONTRACT_KW if Version::V1_3 <= version => true,
            VALUE_KW if Version::V1_5 <= version => true,
            _ => false,
        }
    }
    #[doc = r" Checks whether this syntax kind is a soft keyword for the given version."]
    #[doc = r" Soft keywords are identifiers that are considered keywords only in certain contexts."]
    pub fn is_soft_keyword(self, version: Version) -> bool {
        match self {
            ABSTRACT_KW => true,
            ACTUAL_KW => true,
            ANNOTATION_KW => true,
            BY_KW => true,
            CATCH_KW => true,
            COMPANION_KW => true,
            CONST_KW => true,
            CONSTRUCTOR_KW => true,
            CONTEXT_KW if version < Version::V1_7 => true,
            CROSSINLINE_KW => true,
            DATA_KW => true,
            DELEGATE_KW => true,
            DYNAMIC_KW => true,
            ENUM_KW => true,
            EXPECT_KW => true,
            EXTERNAL_KW => true,
            FIELD_KW => true,
            FILE_KW => true,
            FINAL_KW => true,
            FINALLY_KW => true,
            GET_KW => true,
            IMPORT_KW => true,
            INFIX_KW => true,
            INIT_KW => true,
            INLINE_KW => true,
            INNER_KW => true,
            INTERNAL_KW => true,
            LATEINIT_KW => true,
            NOINLINE_KW => true,
            OPEN_KW => true,
            OPERATOR_KW => true,
            OUT_KW => true,
            OVERRIDE_KW => true,
            PARAM_KW => true,
            PRIVATE_KW => true,
            PROPERTY_KW => true,
            PROTECTED_KW => true,
            PUBLIC_KW => true,
            RECEIVER_KW => true,
            REIFIED_KW => true,
            SEALED_KW => true,
            SET_KW => true,
            SETPARAM_KW => true,
            SUSPEND_KW => true,
            TAILREC_KW => true,
            VALUE_KW if version < Version::V1_5 => true,
            VARARG_KW => true,
            WHERE_KW => true,
            _ => false,
        }
    }
    #[doc = r" Checks whether this syntax kind is a strict or soft keyword for the given version."]
    pub fn is_keyword(self, version: Version) -> bool {
        matches!(
            self,
            AS_KW
                | BREAK_KW
                | CLASS_KW
                | CONTINUE_KW
                | DO_KW
                | ELSE_KW
                | FALSE_KW
                | FOR_KW
                | FUN_KW
                | IF_KW
                | IN_KW
                | INTERFACE_KW
                | IS_KW
                | NULL_KW
                | OBJECT_KW
                | PACKAGE_KW
                | RETURN_KW
                | SUPER_KW
                | THIS_KW
                | THROW_KW
                | TRUE_KW
                | TRY_KW
                | TYPEALIAS_KW
                | TYPEOF_KW
                | VAL_KW
                | VAR_KW
                | WHEN_KW
                | WHILE_KW
                | NOT_IN_KW
                | NOT_IS_KW
                | AS_SAFE_KW
                | RETURN_AT_KW
                | CONTINUE_AT_KW
                | BREAK_AT_KW
                | THIS_AT_KW
                | SUPER_AT_KW
        ) || match self {
            CONTEXT_KW if Version::V1_7 <= version => true,
            CONTRACT_KW if Version::V1_3 <= version => true,
            VALUE_KW if Version::V1_5 <= version => true,
            ABSTRACT_KW => true,
            ACTUAL_KW => true,
            ANNOTATION_KW => true,
            BY_KW => true,
            CATCH_KW => true,
            COMPANION_KW => true,
            CONST_KW => true,
            CONSTRUCTOR_KW => true,
            CONTEXT_KW if version < Version::V1_7 => true,
            CROSSINLINE_KW => true,
            DATA_KW => true,
            DELEGATE_KW => true,
            DYNAMIC_KW => true,
            ENUM_KW => true,
            EXPECT_KW => true,
            EXTERNAL_KW => true,
            FIELD_KW => true,
            FILE_KW => true,
            FINAL_KW => true,
            FINALLY_KW => true,
            GET_KW => true,
            IMPORT_KW => true,
            INFIX_KW => true,
            INIT_KW => true,
            INLINE_KW => true,
            INNER_KW => true,
            INTERNAL_KW => true,
            LATEINIT_KW => true,
            NOINLINE_KW => true,
            OPEN_KW => true,
            OPERATOR_KW => true,
            OUT_KW => true,
            OVERRIDE_KW => true,
            PARAM_KW => true,
            PRIVATE_KW => true,
            PROPERTY_KW => true,
            PROTECTED_KW => true,
            PUBLIC_KW => true,
            RECEIVER_KW => true,
            REIFIED_KW => true,
            SEALED_KW => true,
            SET_KW => true,
            SETPARAM_KW => true,
            SUSPEND_KW => true,
            TAILREC_KW => true,
            VALUE_KW if version < Version::V1_5 => true,
            VARARG_KW => true,
            WHERE_KW => true,
            _ => false,
        }
    }
    pub fn is_punct(self) -> bool {
        matches!(
            self,
            DOLLAR
                | DOT
                | COMMA
                | L_PAREN
                | R_PAREN
                | L_SQUARE
                | R_SQUARE
                | L_CURL
                | R_CURL
                | MULT
                | MOD
                | DIV
                | ADD
                | SUB
                | SUB_ASSIGNMENT
                | INCR
                | DECR
                | CONJ
                | DISJ
                | EXCL
                | COLON
                | SEMICOLON
                | ASSIGNMENT_TOKEN
                | ADD_ASSIGNMENT
                | MULT_ASSIGNMENT
                | DIV_ASSIGNMENT
                | MOD_ASSIGNMENT
                | ARROW
                | RANGE
                | RANGE_UNTIL
                | COLON_COLON
                | AT
                | QUEST
                | L_ANGLE
                | R_ANGLE
                | LE
                | GE
                | EXCL_EQ
                | EXCL_EQ_EQ
                | EQ_EQ
                | EQ_EQ_EQ
                | AMP
                | QUOTE
                | TRIPLE_QUOTE
        )
    }
    pub fn is_literal(self) -> bool {
        matches!(self, BIN | BOOL | CHAR | ESCAPED | FLOAT | HEX | INT | LONG | TEXT | UNSIGNED)
    }
    pub fn from_keyword(ident: &str, version: Version) -> Option<SyntaxKind> {
        let kw = match ident {
            "as" => AS_KW,
            "break" => BREAK_KW,
            "class" => CLASS_KW,
            "continue" => CONTINUE_KW,
            "do" => DO_KW,
            "else" => ELSE_KW,
            "false" => FALSE_KW,
            "for" => FOR_KW,
            "fun" => FUN_KW,
            "if" => IF_KW,
            "in" => IN_KW,
            "interface" => INTERFACE_KW,
            "is" => IS_KW,
            "null" => NULL_KW,
            "object" => OBJECT_KW,
            "package" => PACKAGE_KW,
            "return" => RETURN_KW,
            "super" => SUPER_KW,
            "this" => THIS_KW,
            "throw" => THROW_KW,
            "true" => TRUE_KW,
            "try" => TRY_KW,
            "typealias" => TYPEALIAS_KW,
            "typeof" => TYPEOF_KW,
            "val" => VAL_KW,
            "var" => VAR_KW,
            "when" => WHEN_KW,
            "while" => WHILE_KW,
            "context" if Version::V1_7 <= version => CONTEXT_KW,
            "contract" if Version::V1_3 <= version => CONTRACT_KW,
            "value" if Version::V1_5 <= version => VALUE_KW,
            _ => return None,
        };
        Some(kw)
    }
    pub fn from_contextual_keyword(ident: &str, version: Version) -> Option<SyntaxKind> {
        let kw = match ident {
            "abstract" => ABSTRACT_KW,
            "actual" => ACTUAL_KW,
            "annotation" => ANNOTATION_KW,
            "by" => BY_KW,
            "catch" => CATCH_KW,
            "companion" => COMPANION_KW,
            "const" => CONST_KW,
            "constructor" => CONSTRUCTOR_KW,
            "context" if version < Version::V1_7 => CONTEXT_KW,
            "crossinline" => CROSSINLINE_KW,
            "data" => DATA_KW,
            "delegate" => DELEGATE_KW,
            "dynamic" => DYNAMIC_KW,
            "enum" => ENUM_KW,
            "expect" => EXPECT_KW,
            "external" => EXTERNAL_KW,
            "field" => FIELD_KW,
            "file" => FILE_KW,
            "final" => FINAL_KW,
            "finally" => FINALLY_KW,
            "get" => GET_KW,
            "import" => IMPORT_KW,
            "infix" => INFIX_KW,
            "init" => INIT_KW,
            "inline" => INLINE_KW,
            "inner" => INNER_KW,
            "internal" => INTERNAL_KW,
            "lateinit" => LATEINIT_KW,
            "noinline" => NOINLINE_KW,
            "open" => OPEN_KW,
            "operator" => OPERATOR_KW,
            "out" => OUT_KW,
            "override" => OVERRIDE_KW,
            "param" => PARAM_KW,
            "private" => PRIVATE_KW,
            "property" => PROPERTY_KW,
            "protected" => PROTECTED_KW,
            "public" => PUBLIC_KW,
            "receiver" => RECEIVER_KW,
            "reified" => REIFIED_KW,
            "sealed" => SEALED_KW,
            "set" => SET_KW,
            "setparam" => SETPARAM_KW,
            "suspend" => SUSPEND_KW,
            "tailrec" => TAILREC_KW,
            "value" if version < Version::V1_5 => VALUE_KW,
            "vararg" => VARARG_KW,
            "where" => WHERE_KW,
            _ => return None,
        };
        Some(kw)
    }
    pub fn from_char(c: char) -> Option<SyntaxKind> {
        let tok = match c {
            '$' => DOLLAR,
            '.' => DOT,
            ',' => COMMA,
            '(' => L_PAREN,
            ')' => R_PAREN,
            '[' => L_SQUARE,
            ']' => R_SQUARE,
            '{' => L_CURL,
            '}' => R_CURL,
            '*' => MULT,
            '%' => MOD,
            '/' => DIV,
            '+' => ADD,
            '-' => SUB,
            '!' => EXCL,
            ':' => COLON,
            ';' => SEMICOLON,
            '=' => ASSIGNMENT_TOKEN,
            '@' => AT,
            '?' => QUEST,
            '<' => L_ANGLE,
            '>' => R_ANGLE,
            '&' => AMP,
            '"' => QUOTE,
            _ => return None,
        };
        Some(tok)
    }
}
#[doc = r" `T![]`"]
#[macro_export]
macro_rules ! T_ {
    [$] => { $ crate :: SyntaxKind :: DOLLAR };
    [.] => { $ crate :: SyntaxKind :: DOT };
    [,] => { $ crate :: SyntaxKind :: COMMA };
    ['('] => { $ crate :: SyntaxKind :: L_PAREN };
    [')'] => { $ crate :: SyntaxKind :: R_PAREN };
    ['['] => { $ crate :: SyntaxKind :: L_SQUARE };
    [']'] => { $ crate :: SyntaxKind :: R_SQUARE };
    ['{'] => { $ crate :: SyntaxKind :: L_CURL };
    ['}'] => { $ crate :: SyntaxKind :: R_CURL };
    [*] => { $ crate :: SyntaxKind :: MULT };
    [%] => { $ crate :: SyntaxKind :: MOD };
    [/] => { $ crate :: SyntaxKind :: DIV };
    [+] => { $ crate :: SyntaxKind :: ADD };
    [-] => { $ crate :: SyntaxKind :: SUB };
    [-=] => { $ crate :: SyntaxKind :: SUB_ASSIGNMENT };
    [++] => { $ crate :: SyntaxKind :: INCR };
    [--] => { $ crate :: SyntaxKind :: DECR };
    [&&] => { $ crate :: SyntaxKind :: CONJ };
    [||] => { $ crate :: SyntaxKind :: DISJ };
    [!] => { $ crate :: SyntaxKind :: EXCL };
    [:] => { $ crate :: SyntaxKind :: COLON };
    [;] => { $ crate :: SyntaxKind :: SEMICOLON };
    [=] => { $ crate :: SyntaxKind :: ASSIGNMENT_TOKEN };
    [+=] => { $ crate :: SyntaxKind :: ADD_ASSIGNMENT };
    [*=] => { $ crate :: SyntaxKind :: MULT_ASSIGNMENT };
    [/=] => { $ crate :: SyntaxKind :: DIV_ASSIGNMENT };
    [%=] => { $ crate :: SyntaxKind :: MOD_ASSIGNMENT };
    [->] => { $ crate :: SyntaxKind :: ARROW };
    [..] => { $ crate :: SyntaxKind :: RANGE };
    [..<] => { $ crate :: SyntaxKind :: RANGE_UNTIL };
    [::] => { $ crate :: SyntaxKind :: COLON_COLON };
    [@] => { $ crate :: SyntaxKind :: AT };
    [?] => { $ crate :: SyntaxKind :: QUEST };
    [<] => { $ crate :: SyntaxKind :: L_ANGLE };
    [>] => { $ crate :: SyntaxKind :: R_ANGLE };
    [<=] => { $ crate :: SyntaxKind :: LE };
    [>=] => { $ crate :: SyntaxKind :: GE };
    [!=] => { $ crate :: SyntaxKind :: EXCL_EQ };
    [!==] => { $ crate :: SyntaxKind :: EXCL_EQ_EQ };
    [==] => { $ crate :: SyntaxKind :: EQ_EQ };
    [===] => { $ crate :: SyntaxKind :: EQ_EQ_EQ };
    [&] => { $ crate :: SyntaxKind :: AMP };
    ['"'] => { $ crate :: SyntaxKind :: QUOTE };
    ['"'] => { $ crate :: SyntaxKind :: TRIPLE_QUOTE };
    ["as"] => { $ crate :: SyntaxKind :: AS_KW };
    ["break"] => { $ crate :: SyntaxKind :: BREAK_KW };
    ["class"] => { $ crate :: SyntaxKind :: CLASS_KW };
    ["continue"] => { $ crate :: SyntaxKind :: CONTINUE_KW };
    ["do"] => { $ crate :: SyntaxKind :: DO_KW };
    ["else"] => { $ crate :: SyntaxKind :: ELSE_KW };
    ["false"] => { $ crate :: SyntaxKind :: FALSE_KW };
    ["for"] => { $ crate :: SyntaxKind :: FOR_KW };
    ["fun"] => { $ crate :: SyntaxKind :: FUN_KW };
    ["if"] => { $ crate :: SyntaxKind :: IF_KW };
    ["in"] => { $ crate :: SyntaxKind :: IN_KW };
    ["interface"] => { $ crate :: SyntaxKind :: INTERFACE_KW };
    ["is"] => { $ crate :: SyntaxKind :: IS_KW };
    ["null"] => { $ crate :: SyntaxKind :: NULL_KW };
    ["object"] => { $ crate :: SyntaxKind :: OBJECT_KW };
    ["package"] => { $ crate :: SyntaxKind :: PACKAGE_KW };
    ["return"] => { $ crate :: SyntaxKind :: RETURN_KW };
    ["super"] => { $ crate :: SyntaxKind :: SUPER_KW };
    ["this"] => { $ crate :: SyntaxKind :: THIS_KW };
    ["throw"] => { $ crate :: SyntaxKind :: THROW_KW };
    ["true"] => { $ crate :: SyntaxKind :: TRUE_KW };
    ["try"] => { $ crate :: SyntaxKind :: TRY_KW };
    ["typealias"] => { $ crate :: SyntaxKind :: TYPEALIAS_KW };
    ["typeof"] => { $ crate :: SyntaxKind :: TYPEOF_KW };
    ["val"] => { $ crate :: SyntaxKind :: VAL_KW };
    ["var"] => { $ crate :: SyntaxKind :: VAR_KW };
    ["when"] => { $ crate :: SyntaxKind :: WHEN_KW };
    ["while"] => { $ crate :: SyntaxKind :: WHILE_KW };
    ["!in"] => { $ crate :: SyntaxKind :: NOT_IN_KW };
    ["!is"] => { $ crate :: SyntaxKind :: NOT_IS_KW };
    ["as?"] => { $ crate :: SyntaxKind :: AS_SAFE_KW };
    ["return@"] => { $ crate :: SyntaxKind :: RETURN_AT_KW };
    ["continue@"] => { $ crate :: SyntaxKind :: CONTINUE_AT_KW };
    ["break@"] => { $ crate :: SyntaxKind :: BREAK_AT_KW };
    ["this@"] => { $ crate :: SyntaxKind :: THIS_AT_KW };
    ["super@"] => { $ crate :: SyntaxKind :: SUPER_AT_KW };
    [abstract] => { $ crate :: SyntaxKind :: ABSTRACT_KW };
    [actual] => { $ crate :: SyntaxKind :: ACTUAL_KW };
    [annotation] => { $ crate :: SyntaxKind :: ANNOTATION_KW };
    [by] => { $ crate :: SyntaxKind :: BY_KW };
    [catch] => { $ crate :: SyntaxKind :: CATCH_KW };
    [companion] => { $ crate :: SyntaxKind :: COMPANION_KW };
    [const] => { $ crate :: SyntaxKind :: CONST_KW };
    [constructor] => { $ crate :: SyntaxKind :: CONSTRUCTOR_KW };
    [context] => { $ crate :: SyntaxKind :: CONTEXT_KW };
    [crossinline] => { $ crate :: SyntaxKind :: CROSSINLINE_KW };
    [data] => { $ crate :: SyntaxKind :: DATA_KW };
    [delegate] => { $ crate :: SyntaxKind :: DELEGATE_KW };
    [dynamic] => { $ crate :: SyntaxKind :: DYNAMIC_KW };
    [enum] => { $ crate :: SyntaxKind :: ENUM_KW };
    [expect] => { $ crate :: SyntaxKind :: EXPECT_KW };
    [external] => { $ crate :: SyntaxKind :: EXTERNAL_KW };
    [field] => { $ crate :: SyntaxKind :: FIELD_KW };
    [file] => { $ crate :: SyntaxKind :: FILE_KW };
    [final] => { $ crate :: SyntaxKind :: FINAL_KW };
    [finally] => { $ crate :: SyntaxKind :: FINALLY_KW };
    [get] => { $ crate :: SyntaxKind :: GET_KW };
    [import] => { $ crate :: SyntaxKind :: IMPORT_KW };
    [infix] => { $ crate :: SyntaxKind :: INFIX_KW };
    [init] => { $ crate :: SyntaxKind :: INIT_KW };
    [inline] => { $ crate :: SyntaxKind :: INLINE_KW };
    [inner] => { $ crate :: SyntaxKind :: INNER_KW };
    [internal] => { $ crate :: SyntaxKind :: INTERNAL_KW };
    [lateinit] => { $ crate :: SyntaxKind :: LATEINIT_KW };
    [noinline] => { $ crate :: SyntaxKind :: NOINLINE_KW };
    [open] => { $ crate :: SyntaxKind :: OPEN_KW };
    [operator] => { $ crate :: SyntaxKind :: OPERATOR_KW };
    [out] => { $ crate :: SyntaxKind :: OUT_KW };
    [override] => { $ crate :: SyntaxKind :: OVERRIDE_KW };
    [param] => { $ crate :: SyntaxKind :: PARAM_KW };
    [private] => { $ crate :: SyntaxKind :: PRIVATE_KW };
    [property] => { $ crate :: SyntaxKind :: PROPERTY_KW };
    [protected] => { $ crate :: SyntaxKind :: PROTECTED_KW };
    [public] => { $ crate :: SyntaxKind :: PUBLIC_KW };
    [receiver] => { $ crate :: SyntaxKind :: RECEIVER_KW };
    [reified] => { $ crate :: SyntaxKind :: REIFIED_KW };
    [sealed] => { $ crate :: SyntaxKind :: SEALED_KW };
    [set] => { $ crate :: SyntaxKind :: SET_KW };
    [setparam] => { $ crate :: SyntaxKind :: SETPARAM_KW };
    [suspend] => { $ crate :: SyntaxKind :: SUSPEND_KW };
    [tailrec] => { $ crate :: SyntaxKind :: TAILREC_KW };
    [value] => { $ crate :: SyntaxKind :: VALUE_KW };
    [vararg] => { $ crate :: SyntaxKind :: VARARG_KW };
    [where] => { $ crate :: SyntaxKind :: WHERE_KW };
    [context] => { $ crate :: SyntaxKind :: CONTEXT_KW };
    [contract] => { $ crate :: SyntaxKind :: CONTRACT_KW };
    [value] => { $ crate :: SyntaxKind :: VALUE_KW };
    [lifetime_ident] => { $ crate :: SyntaxKind :: LIFETIME_IDENT };
    [int_number] => { $ crate :: SyntaxKind :: INT_NUMBER };
    [ident] => { $ crate :: SyntaxKind :: IDENT };
    [string] => { $ crate :: SyntaxKind :: STRING };
    [shebang] => { $ crate :: SyntaxKind :: SHEBANG };
    [frontmatter] => { $ crate :: SyntaxKind :: FRONTMATTER };
}

impl ::core::marker::Copy for SyntaxKind {}
impl ::core::clone::Clone for SyntaxKind {
    #[inline]
    fn clone(&self) -> Self { *self }
}
impl ::core::cmp::PartialEq for SyntaxKind {
    #[inline]
    fn eq(&self, other: &Self) -> bool { (*self as u16) == (*other as u16) }
}
impl ::core::cmp::Eq for SyntaxKind {}
impl ::core::cmp::PartialOrd for SyntaxKind {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> core::option::Option<core::cmp::Ordering> {
        Some(self.cmp(other))
    }
}
impl ::core::cmp::Ord for SyntaxKind {
    #[inline]
    fn cmp(&self, other: &Self) -> core::cmp::Ordering { (*self as u16).cmp(&(*other as u16)) }
}
impl ::core::hash::Hash for SyntaxKind {
    fn hash<H: ::core::hash::Hasher>(&self, state: &mut H) {
        ::core::mem::discriminant(self).hash(state);
    }
}
